package sudoku.GUI;

import java.awt.Button;
import sudoku.MotorSudoku;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Bas
 */
public class GUI_Tablero extends javax.swing.JFrame {

    private MotorSudoku motorSudoku = new MotorSudoku();

    /**
     * Creates new form GUI_Tablero
     */
    public GUI_Tablero() {
        initComponents();
        generarCasillas();
        motorSudoku.mostrarTablero();
    }

    private void generarCasillas() {
        for (int f = 0; f < motorSudoku.getTablero().length; f++) {
            for (int c = 0; c < motorSudoku.getTablero().length; c++) {
                Button ventana = new Button(motorSudoku.getTablero()[f][c]);
                ventana.setBounds(55*c, 55*f, 50, 50);
                ventana.setVisible(true);
                this.add(ventana);

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(540, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 291, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
